[[redirects]]
  from = "/api/*"
  to = "https://share-me-pag5.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/assets/*"
  to = "https://share-me-pag5.onrender.com/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
